// react-h5-demo/src/views/demo/img/index.jsx
import React, { useState } from "react";
import { withRouter } from "react-router-dom";
import { connect } from "react-redux";
// import "./index.less";

import img from '@/assets/common/1.jpg'

const Img = (props) => {
  const { userInfo, history } = props;

  const [imgUrl, setImgUrl] = useState(img);

  const codeFilter = (value) => {
    let arr = ['no', 'yes']
    return arr[value] || '-'
  }

  return (
    <div>
      <div>img</div>
      <br />
      <br />
      <div>
        <img src={imgUrl} alt="" />
      </div>
      <br />
      <div> { codeFilter(0) } </div>
  </div>
  );
};


const mapStateToProps = (state) => {
  return {
    ...state.user
  };
};
export default withRouter(
  connect(mapStateToProps)(Img)
);

// vue-h5-demo/src/views/demo/img.vue
<template>
  <div>
    <div>img</div>
		<br />
    <div>
      <img src="@/assets/common/1.jpg" />
    </div>
    <br />
    <div>
      <img :src="imgUrl" />
    </div>
  </div>
</template>

<script>
import img from '@/assets/common/1.jpg'

export default {
  name: 'ajax',
  data() {
    return {
			imgUrl: img 
    }
  },
	filters: {
		codeFilter: function (value) {
			let arr = ['no', 'yes']
			return arr[value] || '-'
		}
	},
  created() {
    this.getData()
  },
  mounted() {
	},
  destoryed() {

  },
  methods: {
    async getData() {
    },    
	},
}
</script>

<style lang="less" scoped>

</style>
