// react-h5-demo/src/views/demo/ref/index.js
import React, { useState, useEffect, useRef } from "react";
import { withRouter } from "react-router-dom";
import { connect } from "react-redux";
import "./index.less";

import Record from '@/components/Record'

const RefPage = (props) => {
  const { userInfo, history } = props;

	const textInput = useRef(null);
	const recordRef = useRef(null);

  const getRef = (item) => {
		console.info(textInput.current.innerText)
		console.info(textInput.current.getAttribute('class'))
		console.info(textInput.current.getAttribute('data-id'))		
  }

  const getRecordRef = (item) => {
		console.info(recordRef)
		recordRef.current.getRef()
  }	

  useEffect(() => {
    console.info(2)
  })

  console.info(1)


  return (
    <div className="RefPage">
			<div className="m-t-10 text-c" onClick={getRef} ref={textInput} data-id="txt">getRef</div>
			<br />
			<Record ref={recordRef} />
			<div className="m-t-6 text-c" onClick={getRecordRef}>getRecordRef</div>
    </div>
  );
};


const mapStateToProps = (state) => {
  return {
    ...state.user
  };
};
export default withRouter(
  connect(mapStateToProps)(RefPage)
);

// vue-h5-demo/src/views/demo/ref.vue
<template>
  <div>
		<record ref="refRecord" />

    <div class="m-t-10 text-c" @click="getRecord" ref="refRecordTxt" data-id="txt">getRecord</div>
  </div>
</template>

<script>
import record from '@/components/record'

export default {
  name: 'refPage',
  data() {
    return {
			code: 1
    }
  },
	components: {
		record
	},	
	filters: {
		codeFilter: function (value) {
			let arr = ['no', 'yes']
			return arr[value] || '-'
		}
	},
  created() {
    this.getData()
  },
  mounted() {
	},
  destoryed() {

  },
  methods: {
    async getData() {
    },  
    getRecord() {
      // 获取dom
      console.info(this.$refs.refRecordTxt)
      console.info(this.$refs.refRecordTxt.innerText)
      console.info(this.$refs.refRecordTxt.getAttribute('class'))
      console.info(this.$refs.refRecordTxt.getAttribute('data-id'))
      console.info('----')
      // 获取子组件方法
      this.$refs.refRecord.getData()
      console.info(this.$refs.numData)
    }  
	},
}
</script>

<style lang="less" scoped>

</style>
