// react-h5-demo/src/components/Pie/index.js
import React, { useState, useEffect } from "react";
import PropTypes from 'prop-types';
import { withRouter } from "react-router-dom";
import { connect } from "react-redux";
import "./index.less";

import * as echarts from 'echarts'

const Pie = (props) => {
  const { userInfo, history } = props;

	let chartObj = null;

  const initChart = () => {
    chartObj = echarts.init(document.getElementById(props.domId));
    setOptions();
  }
  const setOptions = () => {
    let option = {
      backgroundColor: '#FFF',
      // 表格标题
      title: {
        top: 20,
        text: '',
        textStyle: {
          fontWeight: 'normal',
          fontSize: 12,
          color: '#333'
        },
        left: '1%'
      },
      // 点击-提示信息
      tooltip: {
        trigger: 'axis',
        axisPointer: {
          lineStyle: {
            color: '#FFF'
          }
        }
      },
      // 右上角标题
      legend: {
        top: 10,
        icon: 'circle',
        itemWidth: 14,
        itemHeight: 5,
        itemGap: 13,
        right: '4%',
        textStyle: {
          fontSize: 12,
          color: '#333'
        }
      },
      // 折线图形-距离顶部的配置        
      grid: {
        top: 60,
        left: '2%',
        right: '2%',
        bottom: '2%',
        containLabel: true
      },
      xAxis: [{
        type: 'category',
        boundaryGap: true,
        // x轴刻度线 
        axisTick: {
          show: false
        },                   
        axisLine: {
          show: true,
          lineStyle: {
            color: '#E5E5E5'
          }
        },
        axisLabel: {
          margin: 10,
          textStyle: {
            fontSize: 12,
            color: '#333'
          }
        },              
        data: props.xAxisData
      }],
      yAxis: [{
        type: 'value',
        name: props.yAxisName,
        // y轴刻度线
        axisTick: {
          show: false
        },
        axisLine: {
          show: false,
          lineStyle: {
            color: '#333'
          }
        },
        axisLabel: {
          margin: 10,
          textStyle: {
            fontSize: 12,
            color: '#333'
          }
        }
      }],
      series: [
        {
          name: props.seriesName[0],
          type: 'line',
          symbol: 'circle',
          symbolSize: 4,
          showSymbol: true,
          lineStyle: {
            normal: {
              width: 1
            }
          },
          itemStyle: {
            normal: {
              color: props.colorArr[0],
              borderColor: props.colorArr[0],
            }
          },
          data: props.seriesData[0]
      }, 
        {
        name: props.seriesName[1],
        type: 'line',
        symbol: 'circle',
        symbolSize: 4,
        showSymbol: true,
        lineStyle: {
          normal: {
            width: 1
          }
        },
        itemStyle: {
          normal: {
            color: props.colorArr[1],
            borderColor: props.colorArr[1],
          }
        },
        data: props.seriesData[1]
      }, {
        name: props.seriesName[2],
        type: 'line',
        symbol: 'circle',
        symbolSize: 4,
        showSymbol: true,
        lineStyle: {
          normal: {
            width: 1
          }
        },
        itemStyle: {
          normal: {
            color: props.colorArr[2],
            borderColor: props.colorArr[2],
          }
        },
        data: props.seriesData[2]
      }]
    };      
    chartObj.setOption(option)		
  }

  useEffect(()=>{
    // let node = document.getElementById(props.domId)
    initChart()
  })

  const clickOne = () => {
    let { clickItem = () => {} } = props;    
    clickItem('son')
  }

  return (
		<div>
			<div id={props.domId} className="chart"></div>
			<br />
			<div onClick={clickOne}>
				clickItem
			</div>
		</div>
  );
};

Pie.propTypes = {
  domId: PropTypes.string.isRequired,
  // chart: PropTypes.object.isRequired,
  colorArr: PropTypes.array.isRequired,

  seriesName: PropTypes.array.isRequired,
  xAxisData: PropTypes.array.isRequired,
  yAxisName: PropTypes.string.isRequired,
  seriesData: PropTypes.array.isRequired,
  clickItem: PropTypes.func.isRequired
};

export default Pie;

// vue-h5-demo/src/components/pie.vue
<template>
  <div
    :id="domId"
    class="pie"
    :style="{ height: height + 'px', width: width + 'px' }"
  ></div>
</template>

<script>
import echarts from 'echarts'

export default {
  name: 'pie',
  props: {
    height: {
      type: Number,
      default: 450,
    },
    width: {
      type: Number,
      default: 750,
    },
    unit: {
      type: String,
      default: '',
    },
    titleName: {
      type: String,
      default: '饼图',
    },
    clickItem: {
      type: Function,
      default: () => {},
    },
    renderData: {
      type: Array,
      default: function () {
        return [
          {
            name: '图例一',
            value: 40,
          },
          {
            name: '图例二',
            value: 60,
          },
        ]
      },
    },
    legendColor: {
      type: Array,
      default: function () {
        return ['#FFBD1F', '#2BA0FF']
      },
    },
    domId: {
      type: String,
      default: 'pie',
    },
    labelShow: {
      type: Boolean,
      default: true,
    },
    isSoild:{
      type: Boolean,
      default: false,      
    }
  },
  data() {
    return {
      chart: null,
      series: [],
      timer: null,
      chartIndex: 0,
    }
  },
  created() {},
  mounted() {
    this.initChart()
  },
  beforeUnmount() {
    if (!this.chart) {
      return
    }
    this.chart.dispose()
    this.chart = null
  },
  unmounted() {},
  methods: {
    initChart() {
      this.chart = echarts.init(document.getElementById(this.domId))
      this.setOptions()
    },
    setOptions() {
      let arr = []
      this.renderData.map((item, index) => {
        arr.push({
          value: item.value,
          name: item.name,
          itemStyle: {
            color: this.legendColor[index],
          },
        })
      })
      this.series = this.series.concat(arr)

      let option = {
        // backgroundColor: '#FFF',
        type: 'pie',
        title: {
          text: this.titleName,
          textStyle: {
            fontWeight: 'normal',
            fontSize: 12,
            // color: '#fff',
          },
          x: 'center',
          y: 'center',
        },
        tooltip: {
          axisPointer: {
            lineStyle: {
              // color: '#FFF',
            },
          },
          trigger: 'item',
          // formatter: '{c} ({d}%)' + this.unit,
          formatter: '{c}' + this.unit,
        },
        legend: {
          textStyle: {
            fontSize: 12,
            // color: '#fff',
          },
          orient: 'vertical',
          left: 'left',
          top: 30,
        },
        grid: {
          top: 60,
          left: '2%',
          right: '2%',
          bottom: '2%',
          containLabel: true,
        },
        series: [
          {
            name: '',
            type: 'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: true,
            label: {
              show: this.labelShow,
              // formatter: '{c} ({d}%)' + this.unit,
              formatter: '{d}%',
              // color: '#fff',
            },
            itemStyle: {
              fontWeight: 'normal',
              normal: {
                // color: '#fff',
              },
            },
            labelLine: {
              show: true,
            },
            data: this.series,
          },
        ],
      }

      if(this.isSoild) {
        delete option.series[0].radius
        // option.legend = {
        //   textStyle: {
        //     fontSize: 12,
        //     color: '#fff',
        //   },
        //   top: 'bottom',
        // }
      }

      this.chart.setOption(option)

      let that = this
      this.chart.on('click', function (item) {
        clearInterval(that.timer)  
        console.info(item.dataIndex)
        that.chart.dispatchAction({
          type: 'downplay',
          seriesIndex: 0,
        })
        that.chart.dispatchAction({
          type: 'highlight',
          seriesIndex: 0,
          dataIndex: item.dataIndex
        })
        that.chart.dispatchAction({
          type: 'showTip',
          seriesIndex: 0,
          dataIndex: item.dataIndex
        })         

        that.$emit('clickItem', item)
      })

      
      this.chart.on('mouseover', function (item) {
        clearInterval(that.timer)
        that.chart.dispatchAction({
          type: 'downplay',
          seriesIndex: 0,
        })
        that.chart.dispatchAction({
          type: 'highlight',
          seriesIndex: 0,
          dataIndex: item.dataIndex
        })
        that.chart.dispatchAction({
          type: 'showTip',
          seriesIndex: 0,
          dataIndex: item.dataIndex
        })         
      })    
      this.chart.on('mouseout', function (item) {
        that.chart.dispatchAction({
          type: 'downplay',
          seriesIndex: 0,
        })        
        // this.timer = setInterval(function () {
        //   that.chart.dispatchAction({
        //     type: 'downplay',
        //     seriesIndex: 0,
        //   })   
        //   that.chartIndex = that.chartIndex + 1 == that.series.length ? 0 : that.chartIndex + 1     
        //   that.chart.dispatchAction({
        //     type: 'highlight',
        //     seriesIndex: 0,
        //     dataIndex: that.chartIndex,
        //   })
        //   that.chart.dispatchAction({
        //     type: 'showTip',
        //     seriesIndex: 0,
        //     dataIndex: that.chartIndex,
        //   })        
        // }, 5000)
      })         

      this.timer = setInterval(function () {
        that.chart.dispatchAction({
          type: 'downplay',
          seriesIndex: 0,
        })   
        that.chartIndex = that.chartIndex + 1 == that.series.length ? 0 : that.chartIndex + 1     
        that.chart.dispatchAction({
          type: 'highlight',
          seriesIndex: 0,
          dataIndex: that.chartIndex,
        })
        that.chart.dispatchAction({
          type: 'showTip',
          seriesIndex: 0,
          dataIndex: that.chartIndex,
        })        
      }, 5000)
    },
  },
}
</script>

<style lang="less">
</style>
