// vue-pc-admin-demo/src/views/wdrw/wdrw/imgInfo.vue
<template>
  <div class="app-container">
    <el-card shadow="never" class="m-b-10">
      <div class="el-page-header m-b-20">
        <div class="el-page-header__content m-lr-auto">多媒体资料-{{ currentNodeName }}</div>
      </div>
      <el-tabs type="card">
        <el-tab-pane label="影像管理">
          <el-row :gutter="20">
            <el-col :span="10">
              <el-card shadow="never">
                <el-tree :data="imgTreeData" :props="imgTreeDataProps" @node-click="getImgList"></el-tree>
              </el-card>
            </el-col>
            <el-col :span="4">
              <el-card shadow="never">
                <el-button @click="toUloadFile">上传文件</el-button>
              </el-card>
            </el-col>            
          </el-row>
        </el-tab-pane>
        <el-tab-pane label="过程信息">过程信息</el-tab-pane>
      </el-tabs>
    </el-card>
  </div>
</template>
<script>
import {
  loanApprovalInfoGetApprovalDocumentDir,
  loanApprovalInfoGetApprovalDocument,
  loanDocumentUploadFileString,
} from '@/api/wdrw/wdrw'

export default {
  name: 'wdrwWdrwImgInfo',
  filters: {},
  data() {
    return {
      projectId: '',
      currentNodeName: '',
      imgTreeData: [
        // {
        //   label: '一级 1',
        //   children: [
        //     {
        //       label: '二级 1-1',
        //       children: [
        //         {
        //           label: '三级 1-1-1',
        //         },
        //       ],
        //     },
        //   ],
        // },
      ],
      imgTreeDataProps: {
        children: 'children',
        label: 'name',
      },
    }
  },
  created() {
    this.projectId = this.$route.query.projectId
    this.currentNodeName = this.$route.query.currentNodeName
    this.getLoanDocumentDirInfo()
  },
  methods: {
    async getLoanDocumentDirInfo() {
      //自行改接扣调用
      let params = {
        loanApplyId: this.projectId,
        fileNamespace: this.$route.query.space,
        releventFlow: this.$route.query.releventFlow,
        releventFlowNode: this.$route.query.releventFlowNode,
      }
      let apiData = await loanApprovalInfoGetApprovalDocumentDir(params)
      let imgArr = []
      imgArr.push(apiData.data)

      this.imgTreeData = imgArr
    },
    async getImgList(data) {
      if(data.children.length === 0) {
        return
      }
      let params = {
        loanApplyId: this.projectId,
        fileNamespace: this.$route.query.space,
        releventFlow: this.$route.query.releventFlow,
        releventFlowNode: this.$route.query.releventFlowNode,
        dirId: data.id,
      }
      let apiData = await loanApprovalInfoGetApprovalDocument(params)
      console.log(apiData.data)
    },
    toUloadFile() {},
  },
}
</script>
<style lang="scss" scoped>
</style>

// react-pc-admin-demo/src/views/wdrw/wdrw/imgInfo/index.jsx
import React, { Component } from "react";
import { Row, Col, Alert } from "antd";
import { withRouter } from "react-router-dom";
import Qs from 'qs';
import "./index.less";
import {
  loanApprovalInfoGetApprovalDocumentDir,
  loanApprovalInfoGetApprovalDocument,
  // loanDocumentUploadFileString,
  // uploadNew
} from '@/api/wdrw/wdrw'
import { Tree } from 'antd';
const { TreeNode } = Tree;

let imgTreeData = []

class Page extends Component {
  state = {
  };

  componentDidMount() {
    this._isMounted = true;
    this.getLoanDocumentDirInfo();
  }
  componentWillUnmount() {
    this._isMounted = false;
  }

  getLoanDocumentDirInfo = async () => {
    //自行改接扣调用
    console.info(this.props.history.location)
    let search = this.props.history.location.search;
    let query = Qs.parse(search.substring(1, search.length));
    let params = {
      loanApplyId: query.projectId,
      fileNamespace: query.space,
      releventFlow: query.releventFlow,
      releventFlowNode: query.releventFlowNode,
    };
    let apiData = await loanApprovalInfoGetApprovalDocumentDir(params);
    let imgArr = [];
    imgArr.push(apiData.data);

    imgTreeData = imgArr;
  };

  getImgList = async (selectedKeys, info) => {
    // console.log(info.node.props.dataRef);
    let search = this.props.history.location.search;
    let query = Qs.parse(search.substring(1, search.length));
    let params = {
      loanApplyId: query.projectId,
      fileNamespace: query.space,
      releventFlow: query.releventFlow,
      releventFlowNode: query.releventFlowNode,
      dirId: info.node.props.dataRef.id,
    };
    let apiData = await loanApprovalInfoGetApprovalDocument(params)
    console.log(apiData.data)
  };
 
  renderTreeNodes = (data) => {
    return data.map(item => {
      if (item.children) {
        return (
          <TreeNode title={item.name} key={item.id} dataRef={item}>
            {this.renderTreeNodes(item.children)}
          </TreeNode>
        );
      }
      return <TreeNode key={item.id} {...item} dataRef={item} />;
    })
  };

  render() {
    return (
      <div>
        <Row gutter={32}>
          <Col xs={12} sm={12} lg={12}>
            <Tree
              defaultExpandAll={true}
              onSelect={this.getImgList}
            >
              {this.renderTreeNodes(imgTreeData)}
            </Tree>
          </Col>
          <Col xs={12} sm={12} lg={12}>
            <Alert message="demo" type="info" />
          </Col>
        </Row>
      </div>
    );
  }
};

export default withRouter(Page);
