// vue-pc-admin-demo/src/views/wdrw/qxgl/index.vue
<template>
  <div class="app-container">
    <el-card shadow="never" class="m-b-10">
      <div class="el-page-header m-b-20">
        <div class="el-page-header__content m-lr-auto">权限管理</div>
      </div>
      <el-form :inline="true" :model="searchForm" :rules="rules" ref="searchForm" label-width="140px">
        <el-row :gutter="5">
          <el-col :span="8">
            <el-form-item label="角色名称：" prop="name">
              <el-input v-model="searchForm.name" placeholder="角色名称" class="same-form-width"></el-input>
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="5">
          <el-col :span="6" :offset="9">
            <el-form-item>
              <el-button type="primary" @click="searchTable('searchForm')">查询</el-button>
              <el-button @click="resetSearchForm('searchForm')">重置</el-button>
              <el-button type="primary" @click="toAddRole">新增角色</el-button>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </el-card>

    <el-table
      max-height="380"
      v-loading="tableData.tableLoading"
      :data="tableData.tableList"
      border
      fit
      highlight-current-row>
      <el-table-column label="角色名称" align="center">
        <template slot-scope="{row}">
          <span>{{ row.name }}</span>
        </template>
      </el-table-column>
      <el-table-column label="角色描述" align="center">
        <template slot-scope="{row}">
          <span>{{ row.note}}</span>
        </template>
      </el-table-column>
      <el-table-column label="功能权限" align="center">
        <template slot-scope="{row}">
          <span>{{ row.menus}}</span>
        </template>
      </el-table-column>
      <el-table-column label="节点权限" align="center">
        <template slot-scope="{row}">
          <span>{{ row.nodes}}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" align="center">
        <template slot-scope="{row}">
          <el-button @click="toOperate(row)" type="text">修改角色</el-button>
          <el-button @click="toOperate2(row)" type="text">修改车贷权限</el-button>
        </template>
      </el-table-column>
    </el-table>

    <pagination
      v-show="tableData.tableTotal>0"
      :total="tableData.tableTotal"
      :page.sync="searchForm.page"
      :limit.sync="searchForm.pageSize"
      @pagination="getTableList"
    ></pagination>

    <el-dialog title="新增角色" width="600px" append-to-body :visible.sync="dialogFormVisible">
      <el-form :model="dialogForm" :rules="dialogRules" ref="dialogForm" label-width="100px">
        <el-row>
          <el-col :span="12">
            <el-form-item label="角色名称：" prop="name">
              <el-input v-model="dialogForm.name" placeholder="角色名称"></el-input>
            </el-form-item>
          </el-col>         
        </el-row>
        <el-row>
          <el-col :span="24">
            <el-form-item label="角色描述：" prop="note">
              <el-input type="textarea" v-model="dialogForm.note"></el-input>
            </el-form-item>
          </el-col>
        </el-row>        
      </el-form>      
      <div slot="footer" class="dialog-footer">
        <el-button @click="closeDialogForm">取消</el-button>
        <el-button type="primary" @click="saveNewRole" v-show="isNewPerson">新增</el-button>
        <el-button type="primary" @click="saveUpdateRole" v-show="!isNewPerson">保存</el-button>
      </div>
    </el-dialog>    
  </div>
</template>
<script>

import {
  zaRoleList,
  zaRoleAdd,
  zaRoleUpdate,
  roleSetauth,
} from '@/api/wdrw/qxgl'
import Pagination from '@/components/Pagination'

export default {
  name: 'wdrwQxgl',
  filters: {
  },
  components: {
    Pagination,
  },
  data() {
    return {
      searchForm: {
        page: 1,
        pageSize: 10,
        name: '',
      },
      rules: {
      },
      tableData: {
        tableLoading: true,
        tableList: [],
        tableTotal: 0,
      },
      dialogForm: {
        name: '',
        note: '',
        id: ''
      },
      dialogRules: {
        name: [{ required: true, message: '请输入角色信息', trigger: 'blur' }],        
      },
      dialogFormVisible: false,
      isNewPerson: true
    }
  },
  created() {
    this.getTableList()
  },
  methods: {
    resetSearchForm(formName) {
      this.$refs[formName].resetFields()
    },
    searchTable(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          this.getTableList()
        } else {
          console.log('error submit!!')
          return false
        }
      })
    },
    toOperate(row) {
      this.isNewPerson = false
      this.dialogForm = this._.pick(row,['name','note','id'])
      this.openDialogForm()
    },
    toOperate2(row) {

    },
    async getTableList() {
      this.tableData.tableLoading = true

      //自行改接扣调用
      let apiData = await zaRoleList(this.searchForm)
      this.tableData.tableList = apiData.data
      this.tableData.tableTotal = apiData.totalItem
      this.tableData.tableLoading = false
    },
    toAddRole() {
      this.isNewPerson = true
      this.openDialogForm()
    },
    saveNewRole() {
      this.$refs['dialogForm'].validate(async (valid) => {
        if (valid) {
          let newData = await zaRoleAdd(this.dialogForm)
          if(newData) {
            this.$message('添加成功')
            this.closeDialogForm()
            this.getTableList()
          }
        } else {
          console.log('error submit!!')
          return false
        }
      })
    },
    saveUpdateRole() {
      this.$refs['dialogForm'].validate(async (valid) => {
        if (valid) {
          let newData = await zaRoleUpdate(this.dialogForm)
          if(newData) {
            this.$message('修改成功')
            this.closeDialogForm()
            this.getTableList()
          }
        } else {
          console.log('error submit!!')
          return false
        }
      })
    },    
    closeDialogForm() {
      this.dialogFormVisible = false
      this.dialogForm = {
        name: '',
        note: '',
        id: ''      
      }
    },
    openDialogForm() {
      this.dialogFormVisible = true
    }
  },
}
</script>
<style lang="scss" scoped>
</style>

// react-pc-admin-demo/src/views/wdrw/qxgl/index.jsx
import React, { Component } from "react";
import {
  Table,
  Form,
  Button,
  Input,
  Collapse,
  Pagination,
  message,
  Col,
  Row
} from "antd";

import { zaRoleList, zaRoleAdd, zaRoleUpdate } from "@/api/wdrw/qxgl";
import EditForm from "./forms/editForm"
import loadsh from "loadsh";
const { Column } = Table;
const { Panel } = Collapse;
class Page extends Component {
  _isMounted = false; // 这个变量是用来标志当前组件是否挂载
  state = {
    list: [],
    loading: false,
    total: 0,    
    searchForm: {
      page: 1,
      pageSize: 10,
      name: ''
    },

    dialogForm: {
      name: '',
      note: '',
      id: ''
    },
    dialogFormVisible: false,
    dialogFormLoading: false,
    isNewPerson: true    
  };
  componentDidMount() {
    this._isMounted = true;
    this.handleSearch();
  }
  componentWillUnmount() {
    this._isMounted = false;
  }
  filterTitleChange = (e) => {
    let value = e.target.value
    this.setState((state) => ({
      searchForm: {
        ...state.searchForm,
        name: value,
      }
    }));
  };
  changePage = (page, pageSize) => {
    this.setState(
      (state) => ({
        searchForm: {
          ...state.searchForm,
          page,
        },
      }),
      () => {
        this.handleSearch();
      }
    );
  };
  changePageSize = (current, pageSize) => {
    this.setState(
      (state) => ({
        searchForm: {
          ...state.searchForm,
          page: 1,
          pageSize,
        },
      }),
      () => {
        this.handleSearch();
      }
    );
  }; 

  handleSearch = () => {
    this.setState({ loading: true });
    zaRoleList(this.state.searchForm).then((res) => {
      this.setState({ loading: false });
      const list = res.data;
      const total = res.totalItem;
      if (this._isMounted) {
        this.setState({ list, total });
      }
    });
  };  
  handleReset = () => {
    this.setState((state) => ({
      searchForm: {
        ...state.searchForm,
        name: '',
      }
    }));    
  }; 

  toAddRole = () => {
    this.setState({
      isNewPerson: true
    });
    this.openDialogForm()
  }; 

  openDialogForm = () => {
    this.setState({
      dialogFormVisible: true
    });
  };  
  handleEdit = (row) => {
    let dialogForm = loadsh.pick(row,['name','note','id']);
    this.setState((state) => ({
      isNewPerson: false,
      dialogForm: {
        ...dialogForm
      }
    }));
    this.openDialogForm();
  };
  closeDialogForm = () => {
    const { form } = this.formRef.props;
    form.resetFields();
    this.setState({
      dialogFormVisible: false      
    });
  }; 
  saveRole = () => {
    const { form } = this.formRef.props;
    form.validateFields(async (err, fieldsValue) => {
      if (err) {
        return;
      }
      const values = {
        ...fieldsValue
      };
      this.setState({ dialogFormLoading: true });

       if(this.state.isNewPerson) {
        let newData = await zaRoleAdd(values)
        if(newData) {        
          form.resetFields();
          this.setState({ 
            dialogFormVisible: false, 
            dialogFormLoading: false 
          });
          message.success('添加成功')
          this.handleSearch()
        }
        return        
      }

      if(!this.state.isNewPerson) {
        let newData = await zaRoleUpdate(values)
        if(newData) {        
          form.resetFields();
          this.setState({ 
            dialogFormVisible: false, 
            dialogFormLoading: false 
          });
          message.success('修改成功')
          this.handleSearch()
        }
        return        
      }
      
    });
  }; 

  render() {
    return (
      <div>
        <Collapse defaultActiveKey={['1']}>
          <Panel header="权限管理" key="1">
            <Form layout="inline">
              <Row gutter={24}>
                <Col span={8}>
                  <Form.Item label="角色名称:">
                    <Input value={this.state.searchForm.name} onChange={this.filterTitleChange} />
                  </Form.Item>
                </Col>               
              </Row>
              <Row style={{ marginTop: '10px' }}>
                <Col span={24} style={{ textAlign: 'center' }}>
                  <Button type="primary" onClick={this.handleSearch}>
                    查询
                  </Button>
                  <Button style={{ marginLeft: 8 }} onClick={this.handleReset}>
                    重置
                  </Button>
                  <Button style={{ marginLeft: 8 }} type="primary" onClick={this.toAddRole}>
                    新增角色
                  </Button>                  
                </Col>
              </Row>
            </Form>
          </Panel>
        </Collapse>
        <br />

        <Table
          bordered
          rowKey={(record) => record.id}
          dataSource={this.state.list}
          loading={this.state.loading}
          pagination={false}
          scroll={{ y: 380 }}
          size="small"
        >
          <Column title="角色名称" dataIndex="name" key="name" align="center" width={100} />
          <Column title="角色描述" dataIndex="note" key="note" align="center" />
          <Column title="功能权限" dataIndex="menus" key="menus" align="center" />
          <Column title="节点权限" dataIndex="nodes" key="nodes" align="center" />
          <Column title="操作" key="action" align="center" width={200} render={(text, row) => (
            <span>
              <Button type="link" onClick={this.handleEdit.bind(null, row)}>修改角色</Button>
            </span>
          )} />
        </Table>
        <br />
        <div className="m-t-10 m-b-10 text-r">
          <Pagination
            total={this.state.total}
            pageSizeOptions={["10", "20", "30", "50"]}
            showTotal={(total) => `共${total}条数据`}
            onChange={this.changePage}
            current={this.state.searchForm.page}
            onShowSizeChange={this.changePageSize}
            showSizeChanger
            showQuickJumper
            hideOnSinglePage={true}
            size="small"
          />
        </div>
        <EditForm
          currentRowData={this.state.dialogForm}
          wrappedComponentRef={formRef => this.formRef = formRef}
          visible={this.state.dialogFormVisible}
          confirmLoading={this.state.dialogFormLoading}
          onCancel={this.closeDialogForm}
          onOk={this.saveRole}
        />        
      </div>
    );
  }
}

export default Page;
